language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
- oraclejdk7
services: mongodb
script:
- sbt clean coverage test && sbt coverageAggregate
after_success:
- sbt coveralls
env:
  global:
    secure: JP0uzrEMuf0tzcUuT9vqc8JX+RKkUih4FBOMKSQe4BXSjc2NmZuG9pLZLwc0GJK/j+SlIpPvPmRrYja54h0ie1STaw+dkUfgDv/htLiWhV1cnp/Iaj86iiULwqtdb8d2c7/Y/4KfpBpzrZI1hcQad+sO3z7yIkyNuzh7rIt8hX8=
deploy:
  app: scalapostman
  api_key:
    secure: dA3C1tqOHTPLe27oz+k+kKmv2cb061tAoCNE/RfwjVIndxXm3g1NzxnoHjNJXp8YXeEat2lAG4dr6Je0pgDaZaAN1fPeQKdMHxLP2JmBXZHejCBRJYcK+LYepq2pF7P6RdUyBPx68G2RplxG8maPWEeAU3jFICw/C4MKx9tyA2s=
